<?php

	/** 
	 * @file
	 * @brief Contains the EventFilter class
	 */

	namespace ct\models\filters;

	/**
	 * @class EventFilter
	 * @brief The base class for event filters
	 */
	interface EventFilter
	{
		/**
		 * @brief Return the sql query for selecting the events resulting from the filter application
		 * @retval string The sql query 
		 * @note The returned sql query should be directly executable and it should be possible to embed it
		 * in another query (also, as it could be embedded, it should be as efficient as possible)
		 * @note The query should return a table with one 'Id_Event' column containing the events
		 */
		public function get_sql_query();

		/**
		 * @brief Return the table alias to use to embed the temporary table generated by the query 
		 * returned by the get_sql_query
		 * @retval string The alias
		 * @note The class implementing this interface should all return different aliases
		 */
		public function get_table_alias();
	}
