<?php

	/**
	 * @file
	 * @brief Controller class
	 */

	namespace util\mvc;

	use util\superglobals\SG_Get as SG_Get;
	use util\superglobals\SG_Post as SG_Post;
	use util\superglobals\SG_Files as SG_Files;
	use util\superglobals\SG_Cookies as SG_Cookies;
	use util\superglobals\SG_Session as SG_Session;

	use ct\Connection as Connection;

	use \Smarty;

	/**
	 * @class Controller 
	 * @brief Superclass of any controller class
	 */
	abstract class Controller
	{
		protected $sg_get; /**< @brief Superglobal object for $_GET */
		protected $sg_post; /**< @brief Superglobal object for $_POST */
		protected $sg_files; /**< @brief Superglobal object for $_FILES */
		protected $sg_cookies; /**< @brief Superglobal object for $_COOKIES */
		protected $sg_session; /**< @brief Superglobal object for $_SESSION */

		protected $smarty; /**< @brief Smarty object */

		protected $connection; /**< @brief Connection object */

		/**
		 * @brief Construct the Controller object
		 */
		public function __construct()
		{
			$this->sg_get = new SG_Get();
			$this->sg_post = new SG_Post();
			$this->sg_files = new SG_Files();
			$this->sg_cookies = new SG_Cookies();
			$this->sg_session = new SG_Session();	

			$this->smarty = new Smarty();
			$this->smarty->setTemplateDir("views/tpl");
			$this->smarty->setCompileDir("views/compiled");

			$this->connection = Connection::get_instance();
		}

		/**
		 * @brief Returns the output generated by the controller as a string so that it can be sent through http(s)
		 * @retval string The output generated by the controller
		 */
		abstract public function get_output();

		/**
		 * @brief If an action should executed from a request, the code for executing this action should be placed into this function
		 * @retval bool True if the action has succeeded, false otherwise
		 */
		abstract protected function perform_action();
	};